name: "Hello World Workflolw"

#controls when the action will run. Triggers the workflow on push to master or production branch.
# on is used when we need to setup some events

on:
  push:
    branches:
      - master
      - production

jobs:
  hello_word:
    runs-on: ubuntu-latest
    steps:
      - name: "Print hello world"
        run: echo "hello world"
